# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bdf9e987f3c66a819d1b795ba91e0bac"
name = "smart-upload"
application_url = "https://supersentimentally-intercommunicable-charolette.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://supersentimentally-intercommunicable-charolette.ngrok-free.dev/auth/callback"
]
