export const CSV_HEADERS = {
    // product_id: 'ProductId',
    product_id: "ProductShopId",
    product_title: "ProductTitle",
    product_handle: "ProductHandle",
    product_type: "ProductType",
    id: "OverlayId",
    type: "OverlayType",
    image_url: "OverlayImage",
    text: "OverlayText",
    font_family: "OverlayFontFamily",
    font_size: "OverlayFontSize",
    font_color: "OverlayFontColor",
    bg_color: "OverlayBackgroundColor",
    opacity: "OverlayOpacity",
    rotation: "OverlayRotation",
    text_align: "OverlayAlign",
    padding_top: "OverlayPaddingTop",
    padding_right: "OverlayPaddingRight",
    padding_bottom: "OverlayPaddingBottom",
    padding_left: "OverlayPaddingLeft",
    position: "OverlayPosition",
    display_in_collection: "DisplayInCollection",
    display_in_product: "DisplayInProduct",
    display_in_search: "DisplayInSearch",
    scale_in_collection: "ScaleInCollection",
    scale_in_product: "ScaleInProduct",
    scale_in_search: "ScaleInSearch",
    status: "OverlayStatus",
};
